### ISSUE TITLE
Routing & Navbar

### ISSUE THREAD

**Issue by Krillinator** [Krillinator/DigitalStock_Frontend#1]
### User Story

**As a** User, **I want to** be able to Navigate between pages, **so that** the user can get around the website.

### Todo

- [x]  Routes
- [x]  Dynamic Routes & Params
- [x]  Documentation
- [x]  Layout.tsx For Global <Nav> element
- [x] Implementation of Navbar (Design & Functionality)
- [x] Move <Link > components, to its OWN tailwind design
- [ ] Fit to <Main> content 

Documentation: [Routing](https://nextjs.org/docs/app/building-your-application/routing)

**Comment by Krillinator** [comment]
**This idea would work extremely well** with Dynamic parameters for a [Slug] pattern especially [...Slug]

**Comment by Krillinator** [comment]
Feature Implemented and Verified 🎉

**Comment by Krillinator** [comment]
**Idea**: Implement a nav-bar for easier navigation through hyperlinks, with styling.

**Comment by Krillinator** [comment]
Feature Implemented and Verified 🎉
