### ISSUE TITLE
Fetch API, Load Products

### ISSUE THREAD

**Issue by Krillinator** [Krillinator/DigitalStock_Frontend#2]
### User Story

_As a user, I want to see a list of items displayed as cards on the page, so I can easily view product details such as title, description, and price_

### TODO

- [x] interface datatype for Card
- [x] Fetch (Client & Server Components)
- [x] TSX syntax with Card <Component>
- [x] Tailwind Basics (Flexbox)
- [x] Debug images (Stock preferably)
- [ ] Nice to have: Media Query, large screen cards (Grid)

Source: [API](https://dummyjson.com/c/13be-235c-4e6a-924c)
