### ISSUE TITLE
Tailwind Custom Color Theme

### ISSUE THREAD

**Issue by Krillinator** [Krillinator/DigitalStock_Frontend#3]
### User Story

_**As a** developer, **I want to** implement a cohesive color palette **to create** a visually appealing homepage and simplify consistent styling across the application_

### TODO

- [x] Create our own Company Color Theme 
- [x] Research Customization of Tailwind CSS Classes (Colors mainly)
- [x] Implement color theme into application

Documentation: [Source](https://tailwindcss.com/docs/customizing-colors)

**Comment by Krillinator** [comment]
Feature Implemented and Verified 🎉
