### ISSUE TITLE
Button Component

### ISSUE THREAD

**Issue by Krillinator** [Krillinator/DigitalStock_Frontend#7]
### TODO

- [x] Define Custom Button Component
- [ ] Enum approach for Button Component (Props for Primary, Secondary, Tertiary)
- [ ] Optional Icon Button
